source_code:
  - go # done
  - rs # done
  - js # done
  - ts # done
  - tsx # done
  - mjs # done
  - cjs # done
  - jsx # done
  - py # done
  - h # done
  - hpp # done
  - cpp # done
  - c # done
  - rb # done
  - sol # done
  - cl # 8 files- not worth
  - asm # 1 file- not worth

config_build:
  - yml # TODO - ask
  - yaml # TODO - ask
  - toml # TODO - ask
  - sh # TODO - ask
  - bash # TODO - ask
  - mod
  - sum
  - sql
  - cmake
  - xml
  - tf
  - hcl
  - conf
  - ini
  - nix
  - bat # TODO - ask
  - dockerfile # TODO - ask

web_ui: # TODO - ask
  - html
  - vue
  - scss
  - css
  - less
  - styl
  - graphql

notebooks_docs:
  - md # done
  - ipynb # done +/-, we didn't catch only class of functions, not "standalone" code
  - mdx
  - adoc
  - rst
  - org
  - tla
  - puml
  - mmd
  - dot

schemas_dsls:
  - proto
  - cql
  - graphql
  - ipldsch

templates:
  - tpl
  - tmpl
  - j2

data_assets: # TODO voyager have multimodal model - think about it
  - png
  - jpg
  - jpeg
  - gif
  - svg
  - ico
  - webp
  - mov
  - mp4
  - webm
  - woff
  - woff2
  - ttf
  - otf
  - pdf
  - docx
  - pptx
  - csv
  - json
  - ndjson
  - jsonline
  - parquet
  - npz
  - pkl
  - pickle
  - pb
  - bin
  - gz
  - tgz
  - tar
  - zip
  - zst
  - stats
  - dat
  - cbor
  - hex
  - sig
  - asc
  - lock
  - tfstate
  - key
