text:
  type: cloud
  dim: 1024
  provider: openai
  model_name: text-embedding-3-large
  api_key_path: "configs/openai_key.yaml"

code:
  type: cloud
  dim: 1024
  provider: openai
  model_name: text-embedding-3-large
  api_key: "configs/openai_key.yaml"
