text:
  type: cloud
  dim: 1024
  provider: voyager
  model_name: voyage-3-large
  max_tokens: 32000
  api_key_path: "configs/voyager_api_key.yaml"

code:
  type: cloud
  dim: 1024
  provider: voyager
  model_name: voyage-code-3
  max_tokens: 16000
  api_key_path: "configs/voyager_api_key.yaml"
