type: "cloud"
model: "gpt-5-nano"
context_length: 400000
max_completion_tokens: 32000
tool_choice: "auto"
path_to_api_key: "configs/openai_key.yaml"
path_to_prompt_config: "configs/prompt_config.yaml"